---
- name: Hoyolab Checkin Setup
  hosts: hoyolab_checkin
  become: true

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=86400
      changed_when: false

  roles:
    - role: hoyolab_checkin
      tags: hoyolab_checkin
